import { supabase } from '../lib/supabase';
import type { Office, SubscriptionStatus } from '../types';
export interface PlatformMetrics { totalOffices: number; active: number; trials: number; canceled: number; activated: number; activationRate: number; conversionRate: number; mrr: number; }
export interface OperationsInboxItem { id: string; officeId?: string | null; email?: string | null; subject?: string; message?: string; requestType?: string; details?: string; status: string; createdAt: string; }
const invoke = async (action: string, extra: Record<string, unknown> = {}) => { const { data, error } = await supabase.functions.invoke('platform-admin', { body: { action, ...extra } }); if (error) throw error; return data as Record<string, unknown>; };
const mapOffice = (row: Record<string, unknown>): Office => ({ id: String(row.id), name: String(row.name || ''), lawyerName: String(row.lawyer_name || ''), oab: String(row.oab || ''), city: String(row.city || ''), state: String(row.state || ''), whatsapp: String(row.whatsapp || ''), whatsappMessageTemplate: row.whatsapp_message_template ? String(row.whatsapp_message_template) : null, email: String(row.email || ''), areas: Array.isArray(row.areas) ? row.areas as Office['areas'] : [], slug: row.slug ? String(row.slug) : undefined, subscriptionStatus: row.subscription_status as Office['subscriptionStatus'], planCode: row.plan_code as Office['planCode'], ownerUserId: String(row.owner_user_id), createdAt: String(row.created_at), updatedAt: String(row.updated_at) });
export const listPlatformOffices = async () => { const data = await invoke('offices'); return { offices: ((data.offices || []) as Record<string, unknown>[]).map(mapOffice) }; };
export const setPlatformOfficeStatus = async (officeId: string, status: SubscriptionStatus) => invoke('set-status', { officeId, status }) as Promise<{ status: string }>;
export const getPlatformMetrics = async () => invoke('metrics') as unknown as PlatformMetrics;
export const listOperationsInbox = async () => invoke('inbox') as Promise<{ privacyRequests: OperationsInboxItem[]; supportTickets: OperationsInboxItem[]; integrationErrors: OperationsInboxItem[] }>;
export const updateOperationsInboxItem = async (kind: 'privacy' | 'support', id: string, status: string, resolutionNote = '') => invoke('inbox-update', { kind, id, status, resolutionNote }) as Promise<{ status: string }>;
