import React, { useMemo, useState } from 'react';
import { Check, Clock3 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useOperationalAlarms } from '../hooks/useOperationalAlarms';
import { listOperationalAlarmEvents } from '../services/supabaseAlarms';
import type { OperationalAlarmEvent } from '../types';

export function Alarms() {
  const { active, loading, error, refresh, markRead, acknowledge, resolve, snooze } = useOperationalAlarms();
  const [severity, setSeverity] = useState<'ALL' | 'INFO' | 'WARNING' | 'CRITICAL'>('ALL');
  const [query, setQuery] = useState('');
  const [history, setHistory] = useState<Record<string, OperationalAlarmEvent[]>>({});
  const filtered = useMemo(() => active.filter(({ alarm }) => (severity === 'ALL' || alarm.severity === severity) && `${alarm.title} ${alarm.message} ${alarm.ruleCode}`.toLowerCase().includes(query.toLowerCase())), [active, query, severity]);
  return <div className="max-w-5xl mx-auto space-y-5"><div><h1 className="text-2xl font-bold text-slate-900">Central de atenção</h1><p className="text-sm text-slate-500 mt-1">Pendências operacionais do escritório, com histórico e responsável.</p></div>
    <div className="flex flex-col gap-2 sm:flex-row"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar alerta…" className="h-9 flex-1 rounded-md border border-slate-200 px-3 text-sm outline-none focus:border-brand-500" /><select value={severity} onChange={event => setSeverity(event.target.value as typeof severity)} className="h-9 rounded-md border border-slate-200 px-3 text-sm"><option value="ALL">Todas as severidades</option><option value="CRITICAL">Críticas</option><option value="WARNING">Avisos</option><option value="INFO">Informativas</option></select></div>
    {error && <div className="flex items-center justify-between gap-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700"><span>Não foi possível atualizar a Central agora.</span><button onClick={() => void refresh()} className="font-semibold underline">Tentar novamente</button></div>}
    {loading ? <div className="text-sm text-slate-500">Carregando alertas…</div> : !filtered.length ? <div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">{active.length ? 'Nenhum alerta corresponde aos filtros.' : 'Tudo em dia por aqui.'}</div> : <div className="space-y-3">{filtered.map(({ alarm, recipient }) => <article key={alarm.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className={`mt-1.5 w-2.5 h-2.5 rounded-full shrink-0 ${alarm.severity === 'CRITICAL' ? 'bg-red-600' : alarm.severity === 'WARNING' ? 'bg-amber-500' : 'bg-blue-500'}`} /><div><h2 className="font-semibold text-slate-900">{alarm.title}</h2><p className="text-sm text-slate-600 mt-1">{alarm.message}</p><p className="text-xs text-slate-400 mt-2">Regra {alarm.ruleCode} · {alarm.state === 'ACKNOWLEDGED' ? 'Em atendimento' : 'Aberto'}</p></div></div><div className="flex flex-wrap gap-2"><button className="px-2.5 py-1.5 text-xs rounded-md border border-slate-200" onClick={() => void markRead(alarm.id)}>Marcar lido</button><button className="px-2.5 py-1.5 text-xs rounded-md border border-slate-200" onClick={() => void snooze(alarm.id)}><Clock3 className="inline w-3 h-3 mr-1" />1 h</button>{alarm.state === 'OPEN' && <button className="px-2.5 py-1.5 text-xs rounded-md bg-brand-700 text-white" onClick={() => void acknowledge(alarm.id, alarm.version)}>Assumir</button>}<button className="px-2.5 py-1.5 text-xs rounded-md bg-slate-900 text-white" onClick={() => void resolve(alarm.id, alarm.version)}><Check className="inline w-3 h-3 mr-1" />Resolver</button><button className="px-2.5 py-1.5 text-xs rounded-md border border-slate-200" onClick={() => void (history[alarm.id] ? setHistory(current => { const next = { ...current }; delete next[alarm.id]; return next; }) : listOperationalAlarmEvents(alarm.id).then(events => setHistory(current => ({ ...current, [alarm.id]: events }))))}>Histórico</button>{alarm.actionPath && <Link to={alarm.actionPath} className="px-2.5 py-1.5 text-xs rounded-md text-brand-700">Abrir origem</Link>}</div></div>{history[alarm.id] && <div className="mt-3 border-t border-slate-100 pt-3 space-y-2">{history[alarm.id].map(event => <div key={event.id} className="flex justify-between gap-3 text-xs text-slate-500"><span>{event.eventType}{event.reason ? ` · ${event.reason}` : ''}</span><time>{new Date(event.createdAt).toLocaleString('pt-BR')}</time></div>)}</div>}</article>)}</div>}
  </div>;
}
