import React, { useMemo, useState } from 'react';
import { KeyRound, ShieldCheck } from 'lucide-react';
import { multiFactor, PhoneAuthProvider, PhoneMultiFactorGenerator, RecaptchaVerifier } from 'firebase/auth';
import { auth } from '../lib/firebase';
import { PageHeader } from '../components/layout/PageHeader';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { Input } from '../components/ui/Input';
import { Button } from '../components/ui/Button';
import { useToast } from '../context/ToastContext';

export const Security = () => {
  const { showToast } = useToast();
  const factors = useMemo(() => auth.currentUser ? multiFactor(auth.currentUser).enrolledFactors : [], [auth.currentUser]);
  const [phone, setPhone] = useState(''); const [code, setCode] = useState(''); const [verificationId, setVerificationId] = useState(''); const [loading, setLoading] = useState(false);
  const sendCode = async () => { if (!auth.currentUser) return; setLoading(true); try { const session = await multiFactor(auth.currentUser).getSession(); const verifier = new RecaptchaVerifier(auth, 'mfa-enroll-recaptcha', { size: 'invisible' }); try { setVerificationId(await new PhoneAuthProvider(auth).verifyPhoneNumber({ phoneNumber: phone, session }, verifier)); showToast('Código enviado por SMS.', 'success'); } finally { verifier.clear(); } } catch (error) { console.error(error); showToast('Não foi possível iniciar o MFA. Confirme o telefone com DDI e a configuração do Firebase.', 'error'); } finally { setLoading(false); } };
  const enroll = async () => { if (!auth.currentUser || !verificationId) return; setLoading(true); try { const credential = PhoneAuthProvider.credential(verificationId, code); await multiFactor(auth.currentUser).enroll(PhoneMultiFactorGenerator.assertion(credential), `Telefone final ${phone.slice(-4)}`); showToast('Segundo fator ativado.', 'success'); window.location.reload(); } catch (error) { console.error(error); showToast('Código inválido ou expirado.', 'error'); } finally { setLoading(false); } };
  const unenroll = async (uid: string) => { if (!auth.currentUser || !window.confirm('Remover este segundo fator?')) return; try { await multiFactor(auth.currentUser).unenroll(uid); showToast('Segundo fator removido.', 'success'); window.location.reload(); } catch (error) { console.error(error); showToast('Não foi possível remover o fator.', 'error'); } };
  return <div className="mx-auto max-w-4xl space-y-6 pb-12"><PageHeader title="Segurança da conta" description="Ative uma segunda verificação para reduzir o risco de acesso indevido." breadcrumbItems={[{ label: 'Segurança' }]} /><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-4 w-4" />Segundo fator por SMS</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-slate-600">O recurso depende de MFA/SMS habilitado no Firebase Authentication. Códigos e telefone são processados pelo provedor de autenticação, não pelo CRM.</p>{factors.map(factor => <div key={factor.uid} className="flex items-center justify-between rounded-lg bg-emerald-50 p-4 text-sm"><span className="font-semibold text-emerald-800">{factor.displayName || 'Telefone cadastrado'}</span><button className="font-semibold text-red-600" onClick={() => unenroll(factor.uid)}>Remover</button></div>)}{factors.length === 0 && <div className="space-y-3"><Input placeholder="+5535999999999" value={phone} onChange={event => setPhone(event.target.value)} />{!verificationId ? <Button disabled={loading || !/^\+[1-9]\d{7,14}$/.test(phone)} onClick={sendCode}><KeyRound className="mr-2 h-4 w-4" />Enviar código</Button> : <div className="flex gap-3"><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="Código de 6 dígitos" value={code} onChange={event => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} /><Button disabled={loading || code.length !== 6} onClick={enroll}>Ativar MFA</Button></div>}</div>}<div id="mfa-enroll-recaptcha" /></CardContent></Card></div>;
};
