import { CalendarEvent, ClientPortalAccess, FinancialRecord, Lead, LeadDocument, LeadEvent, Office, Task, User } from './types';

export const mockUser: User = {
  id: 'u1',
  name: 'Dr. João Silva',
  email: 'joao@silvaadvogados.com.br',
  role: 'admin',
  officeId: 'o1',
  createdAt: new Date().toISOString(),
};

export const mockOffice: Office = {
  id: 'o1',
  name: 'Silva & Advogados Associados',
  lawyerName: 'João Silva',
  oab: 'OAB/SP 123456',
  city: 'São Paulo',
  state: 'SP',
  whatsapp: '11999999999',
  email: 'contato@silvaadvogados.com.br',
  areas: ['Direito Trabalhista', 'Direito de Família', 'Direito do Consumidor'],
  subscriptionStatus: 'TRIALING',
  trialStartedAt: new Date().toISOString(),
  trialEndsAt: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
  subscriptionUpdatedAt: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    officeId: 'o1',
    name: 'Maria Oliveira',
    phone: '11988887777',
    email: 'maria.oliveira@email.com',
    city: 'São Paulo',
    state: 'SP',
    source: 'WhatsApp',
    area: 'Direito Trabalhista',
    status: 'Novo contato',
    priority: 'Alta',
    responsibleUserId: 'u1',
    summary: 'Demitida sem justa causa, empresa não pagou rescisão.',
    notes: 'Cliente muito preocupada com os prazos.',
    consentLgpd: true,
    nextActionText: 'Ligar para entender os detalhes do contrato de trabalho',
    nextActionAt: today.toISOString(),
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
  },
  {
    id: 'l2',
    officeId: 'o1',
    name: 'Carlos Mendes',
    phone: '11977776666',
    email: 'carlos.mendes@email.com',
    city: 'Campinas',
    state: 'SP',
    source: 'Landing Page',
    area: 'Direito de Família',
    status: 'Aguardando triagem',
    priority: 'Média',
    summary: 'Dúvidas sobre pensão alimentícia.',
    notes: '',
    consentLgpd: true,
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
  },
  {
    id: 'l3',
    officeId: 'o1',
    name: 'Fernanda Costa',
    phone: '11966665555',
    email: 'fernanda@email.com',
    city: 'São Paulo',
    state: 'SP',
    source: 'Instagram',
    area: 'Direito do Consumidor',
    status: 'Consulta agendada',
    priority: 'Baixa',
    responsibleUserId: 'u1',
    summary: 'Voo cancelado, perdeu compromisso de trabalho.',
    notes: 'Já enviou os bilhetes por e-mail.',
    consentLgpd: true,
    nextActionText: 'Realizar consulta online',
    nextActionAt: tomorrow.toISOString(),
    createdAt: yesterday.toISOString(),
    updatedAt: today.toISOString(),
  }
];

export const mockEvents: LeadEvent[] = [
  {
    id: 'e1',
    officeId: 'o1',
    leadId: 'l1',
    type: 'created',
    description: 'Lead criado no sistema',
    createdBy: 'Sistema',
    createdAt: today.toISOString(),
  },
  {
    id: 'e2',
    officeId: 'o1',
    leadId: 'l3',
    type: 'status_changed',
    description: 'Status alterado para "Consulta agendada"',
    createdBy: 'u1',
    createdAt: today.toISOString(),
  }
];

export const mockTasks: Task[] = [
  {
    id: 'task1',
    officeId: 'o1',
    leadId: 'l1',
    title: 'Confirmar dados do contrato de trabalho',
    dueAt: today.toISOString(),
    done: false,
    createdAt: today.toISOString(),
  },
  {
    id: 'task2',
    officeId: 'o1',
    leadId: 'l3',
    title: 'Revisar comprovantes enviados pela cliente',
    dueAt: tomorrow.toISOString(),
    done: false,
    createdAt: yesterday.toISOString(),
  },
  {
    id: 'task3',
    officeId: 'o1',
    leadId: 'l2',
    title: 'Retornar sobre documentos de pensão alimentícia',
    dueAt: yesterday.toISOString(),
    done: true,
    createdAt: yesterday.toISOString(),
    completedAt: today.toISOString(),
  },
];

export const mockDocuments: LeadDocument[] = [
  {
    id: 'd1',
    officeId: 'o1',
    leadId: 'l1',
    name: 'Termo de rescisão.pdf',
    fileName: 'termo-rescisao.pdf',
    contentType: 'application/pdf',
    size: 286720,
    storagePath: 'mock/termo-rescisao.pdf',
    downloadUrl: '#',
    category: 'Comprovante',
    visibleInPortal: true,
    uploadedBy: 'u1',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
  },
  {
    id: 'd2',
    officeId: 'o1',
    leadId: 'l3',
    name: 'Bilhetes e comprovantes.pdf',
    fileName: 'bilhetes-comprovantes.pdf',
    contentType: 'application/pdf',
    size: 192512,
    storagePath: 'mock/bilhetes-comprovantes.pdf',
    downloadUrl: '#',
    category: 'Comprovante',
    visibleInPortal: false,
    uploadedBy: 'u1',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal1',
    officeId: 'o1',
    leadId: 'l1',
    title: 'Retorno para Maria Oliveira',
    type: 'Retorno',
    status: 'Agendado',
    startAt: today.toISOString(),
    endAt: null,
    location: 'WhatsApp',
    notes: 'Confirmar documentos de rescisão.',
    responsibleUserId: 'u1',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
  },
  {
    id: 'cal2',
    officeId: 'o1',
    leadId: 'l3',
    title: 'Consulta online com Fernanda Costa',
    type: 'Consulta',
    status: 'Agendado',
    startAt: tomorrow.toISOString(),
    endAt: null,
    location: 'Google Meet',
    notes: 'Revisar comprovantes antes da reunião.',
    responsibleUserId: 'u1',
    createdAt: yesterday.toISOString(),
    updatedAt: today.toISOString(),
  },
];

export const mockFinancialRecords: FinancialRecord[] = [
  {
    id: 'fin1',
    officeId: 'o1',
    leadId: 'l3',
    type: 'Consulta',
    status: 'Em aberto',
    description: 'Consulta inicial online',
    amount: 350,
    dueAt: tomorrow.toISOString(),
    paidAt: null,
    paymentMethod: 'Pix',
    notes: 'Enviar chave Pix após confirmação.',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
  },
  {
    id: 'fin2',
    officeId: 'o1',
    leadId: 'l1',
    type: 'Honorários',
    status: 'Previsto',
    description: 'Honorários trabalhistas iniciais',
    amount: 1800,
    dueAt: tomorrow.toISOString(),
    paidAt: null,
    paymentMethod: 'Transferência',
    notes: '',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
  },
];

export const mockPortalAccesses: ClientPortalAccess[] = [
  {
    id: 'portal-demo',
    officeId: 'o1',
    leadId: 'l1',
    clientName: 'Maria Oliveira',
    clientEmail: 'maria.oliveira@email.com',
    statusLabel: 'Documentos em análise',
    publicNotes: 'Recebemos os documentos iniciais. O escritório fará contato para confirmar os próximos passos.',
    pendingItems: ['Enviar comprovante de pagamento do último salário'],
    documents: [
      {
        id: 'd1',
        name: 'Termo de rescisão.pdf',
        category: 'Comprovante',
        downloadUrl: '#',
        contentType: 'application/pdf',
        size: 286720,
        uploadedAt: today.toISOString(),
      },
    ],
    appointments: [
      {
        id: 'cal1',
        title: 'Retorno para Maria Oliveira',
        type: 'Retorno',
        startAt: today.toISOString(),
        endAt: null,
        location: 'WhatsApp',
      },
    ],
    isActive: true,
    expiresAt: null,
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
  },
];
